### ISSUE TITLE
Markdown code tag should use ```csharp instead of ```C#

### ISSUE THREAD

**Issue by lazlo-bonin** [Doraku/DefaultDocumentation#10]
Most Markdown flavors, including GitHub Flavored Markdown, do not recognize `C#` as a language.

Some recognize `cs`, but most recognize the more explicit `csharp`.

The generated markdown should therefore use blocks like:

```
```csharp
```

Instead of:

```
```C#
```

**Comment by Doraku** [comment]
5483cfeb2f4c82a2d6a26c645fd4f8f7ea77804c
