### ISSUE TITLE
index.md excluded in rebuild even if reset with DefaultDocumentationAssemblyPageName

### ISSUE THREAD

**Issue by emersonbottero** [Doraku/DefaultDocumentation#100]
I'm struggling because I'm using vitepress and there is no way to change the index file the be something else.. 
I do have the option here to rename but then the rebuild excludes index.md even if reset.

**Comment by Doraku** [comment]
What do you mean by exclude and reset? DefaultDocumentation just create a page for the assembly with `index.md` as the default name (configurable via `DefaultDocumentationAssemblyPageName`). I don't know anything about vitepress, a quick search tells me it is a static site generator using markdown so I guess you expect your site to be automatically updated as the documentation is regenerated?

**Comment by emersonbottero** [comment]
If I set te filename to something else like baseindex and create my own index.md by hand.. when I rebuild the solution the index.md file I created is also deleted.

**Comment by Doraku** [comment]
ah ok I get it, yeah all *.md files are deleted from the output directory so if you remove types/members you don't end up with old documentation no longer relevant. I guess you could work around this by adding a post build event to copy your own index.md file to the documentation folder from a different one. With the next version you will be able to provide your own `IFileNameFactory` implementation with a custom clean logic so you could do that also.

**Comment by emersonbottero** [comment]
Ok.
That's a good idea.
