### ISSUE TITLE
Folder Structure Links

### ISSUE THREAD

**Issue by bwood4** [Doraku/DefaultDocumentation#104]
Hey I'm messing around with your FolderFilenameFactory sample (From #94), and it looks like the links generated on docs within subfolders don't work because the links aren't relative paths.

So if I have a structure like this:
OutputFolder\\
----TopLevel.md
----TopLevel\\
--------SubLevel.md

The link in SubLevel.md to TopLevel.md is still just "TopLevel.md" rather than "../TopLevel.md". 

Adding some code in the markdown generation to use relative paths would be a little more robust to different configurations, but if there's a way to solve this with a plugin I'd be happy with that too.

This tool is awesome BTW, thank you for your work!

**Comment by Doraku** [comment]
oh that's a big shortcoming of the sample :/ You should be able to fix this with a custom `IUrlFactory` to replace the existing one for `DocItem`.
```csharp
    public sealed class DocItemAbsoluteFactory : IUrlFactory
    {
        // so it override the default one
        public string Name => "DocItem";

        public string GetUrl(IGeneralContext context, string id)
        {
            if (!context.Items.TryGetValue(id, out DocItem item))
            {
                return null;
            }

            if (item is ExternDocItem externItem)
            {
                return externItem.Url;
            }

            DocItem pagedItem = item;
            while (!pagedItem.HasOwnPage(context))
            {
                pagedItem = pagedItem.Parent;
            }

           // only difference with the default implementation is that you should append the links base url to all urls to make them absolute instead of relative
           // since the urls are only generated once and cached for later use, there's no way to make them aware of a relative page change
            string url = context.Settings.LinksBaseUrl + context.GetFileName(pagedItem);
            if (context.GetRemoveFileExtensionFromUrl() && Path.HasExtension(url))
            {
                url =url.Substring(0, url.Length - Path.GetExtension(url).Length);
            }
            if (item != pagedItem)
            {
                url += "#" + PathCleaner.Clean(item.FullName, context.GetInvalidCharReplacement());
            }

            return url;
        }
    }
```
I have not tested the code above but hopefully it should help you make it works

**Comment by bwood4** [comment]
Took a couple things to get that method to work:
1. ``PathCleaner`` is internal
2. ``GetRemoveFileExtensionFromUrl()`` and ``GetInvalidCharReplacement()`` were both unavailable, maybe from a different assembly?

I copied the code for those over to my plugin and got it working.

I guess with this method you'd want to put the Url of your repo in LinksBaseUrl? This didn't seem to work in my use case (I'm putting it into an AzureDevops wiki). The wiki actually generates a unique id for each page URL and doesn't use the path, so linking to an absolute URL doesn't play nicely.

One possibility of getting relative paths if you are interested could be to change the ``AppendLink()`` extension methods of ``IWriter``, and add extension methods to ``IContext`` that accept a secondary ``DocItem`` or id. The urls generated are already in a psuedo-absolute format, so when appending the links, the cached url of the desired link and the cached url of the ``IWriters`` current ``DocItem`` could be used to determine the actual relative path using something like ``Path.GetRelativePath()`` (available with .Net Standard 2.1, but there are other implementation floating around).

Something like this:
```csharp
public static class IGeneralContextExtension
{
    public static string GetUrl(this IGeneralContext context, DocItem relativeToItem, DocItem item)
        => Path.GetRelativePath(Path.GetDirectoryName(context.GetUrl(relativeToItem)), context.GetUrl(item));
}
```

And then use that in the ``AppendLink()`` methods of the writer:
```csharp
public static class IWriterExtensions
{
    public static IWriter AppendLink(this IWriter writer, DocItem item, string displayedName = null) 
        => writer.AppendUrl(writer.Context.GetUrl(writer.DocItem, item), displayedName ?? item.Name, item.FullName);
}
```

You wouldn't have to change any API, although adding a setting to turn this off and on might be good in case people want the absolute urls.

**Comment by aremes** [comment]
I'd very much appreciate relative paths in this case too. I have a similar setup  using a modified version of the FolderFilenameFactory sample. Absolute URLs are not an option in my case.

**Comment by Doraku** [comment]
see https://github.com/Doraku/DefaultDocumentation/issues/107#issuecomment-1160889885 for comment

**Comment by IdkGoodName** [comment]
Wouldn't it make more sense to have
```
Out
|- SomeType
    |- index.md
    |- SomeProperty.md
```
rather than
```
Out
|- SomeType.md
|- SomeType
    |- SomeProperty.md
```
?

**Comment by Doraku** [comment]
I mean that's up to you I just made a example of how to implement it (in the simplest way) in the sample :)

**Comment by aremes** [comment]
Hi @IdkGoodName !

This is what i needed too, so i thought i'd give you a hint to get you started.. basically, in you FileNameFactory implementation, you'd have to check for the type of documentitem and then set the filename to "index.md" manually. The thing is, this depends on the structure you're generating (`<DefaultDocumentationGeneratedPages>` setting). In my case, i'm not generating separate pages for properties so i'm only using index.md on AssemblyDocItem and NamespaceDocItem. In your case you'd  probably have to do it for TypeDocItem as well.

Here's the relevant part of my own FolderFileNameFactory
```csharp
public string GetFileName(IGeneralContext context, DocItem item)
{
	if(item is null)
		throw new ArgumentNullException(nameof(item));
	if(item is NamespaceDocItem || item is AssemblyDocItem)
	{
		return Path.Combine(item.FullName.Split('.').Concat(Enumerable.Repeat("index.md", 1)).ToArray());
	}
	else
	{
		//proceed as usual
	}
}
```

**Comment by juliansangillo** [comment]
I am trying to implement my own FolderFileNameFactory in my plugin and am running into this issue as well. It would be great if we could find a solution to this.
