### ISSUE TITLE
VB Project Issue

### ISSUE THREAD

**Issue by bwood4** [Doraku/DefaultDocumentation#106]
VB projects don't have the intermediate path prepended to the DocumentationFile property, which causes the DefaultDocumentation task to break because it can't find the file (see [this issue](https://github.com/dotnet/sdk/issues/1598)). Altering the DefaultDocumentation target to the following would fix it:

```xml
<_DefaultDocumentationDocumentationFile Condition="'$(MSBuildProjectExtension)' == '.vbproj'">$([System.IO.Path]::GetFullPath($(IntermediateOutputPath)$(DocumentationFile)))</_DefaultDocumentationDocumentationFile>
<_DefaultDocumentationDocumentationFile Condition="'$(MSBuildProjectExtension)' != '.vbproj'">$([System.IO.Path]::GetFullPath($(DocumentationFile)))</_DefaultDocumentationDocumentationFile>
```

**Comment by Doraku** [comment]
Sure I never intended for DefaultDocumentation to be used by vbproj or fsproj as it produces code snippet in c# only but with plugins people could change that. If all it requires to work with vbproj is this simple change I will gladly take it :) thanks for the heads-up.
