### ISSUE TITLE
Inline <code> blocks break Markdown layout

### ISSUE THREAD

**Issue by lazlo-bonin** [Doraku/DefaultDocumentation#11]
For example:

![image](https://user-images.githubusercontent.com/3683308/68164504-f378cb80-ff2a-11e9-91f2-91245671356d.png)

---

Results in:

![image](https://user-images.githubusercontent.com/3683308/68164527-fd023380-ff2a-11e9-9968-7e87447ef01b.png)

---

When they do not contain line breaks, I believe &lt;code&gt; tags should output ``inline`` code markers instead of code blocks.

**Comment by Doraku** [comment]
I tried to stay true to the documentation of microsoft on the xml decoration.
As stated [here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/code-inline) for inlined code you should use `<c>` while `<code>` is for multiline code.
