### ISSUE TITLE
DefaultDocumentationFileNameMode broken

### ISSUE THREAD

**Issue by BigGuyWithBeard** [Doraku/DefaultDocumentation#111]
Hi,
Im having an issue with the DefaultDocumentationFileNameMode setting in v0.8.1 
Im getting the 'filename too long' issue, using 'Name' as the value,  but filename are unchanged.
I've tried rolling back to version 0.7.9 and this version does change the file name nicely.

**Comment by Doraku** [comment]
This is one of the numerous breaking changes that happened with v0.8.0, the new name of this property is `DefaultDocumentationFileNameFactory` as stated in the readme, sorry for the confusion :(
