### ISSUE TITLE
Unhandled Exception if additional leading whitespace between <summary> tags

### ISSUE THREAD

**Issue by Tamnavulin** [Doraku/DefaultDocumentation#12]
**When it happens:**
If you comment a variable like this:
/// &lt;summary&gt;
/// _**<-- this is an additional whitespace** before the comment text starts
/// &lt;summary&gt;

**What happens:**
In this case there will be an exception in DocumentationWriter.cs Line 204

**FIX:** 
check length (value) of variable"startIndex" in code

**Example:**
`summary = string.Join(Environment.NewLine, lines.Skip(firstLine).Select(l => l.StartsWith(" ") ? l.Substring(startIndex > l.Length ? l.Length : startIndex) : l));`

**Comment by Doraku** [comment]
b9cb8d252581071b91ea34fc850075ff84cb7683
thanks, good catch!
Problem of leading whitespace in the first comment line is that it may remove characters of following lines as it change the start index
```
/// <summary>
///    first line is starting later
///  12345 second line
/// </summary>
```
would end up as
>first line is starting later
345 second line

in the generated documentation, but I think I can live with that for now.
