### ISSUE TITLE
Is there a way to eliminate single-line breaks from doc comments?

### ISSUE THREAD

**Issue by madelson** [Doraku/DefaultDocumentation#120]
When writing C# doc comments, I manually wrap text to keep lines from getting too long (e.g. [this file](https://github.com/madelson/DistributedLock/blob/default-documentation/DistributedLock.Azure/AzureBlobLeaseOptionsBuilder.cs#L66)). However, this wrapping is preserved in the output markdown files, which [looks a bit awkward](https://github.com/madelson/DistributedLock/blob/default-documentation/docs/api/DistributedLock.Azure/AzureBlobLeaseOptionsBuilder.BusyWaitSleepTime.mMUlB7vk6GdAQl9sAcmgNg.md). 

Any thoughts on how to improve the formatting? Ideally for me the tool would retain paragraph breaks but not retain line breaks except in `<code>` blocks.

**Comment by Doraku** [comment]
There's a [setting just for that](https://github.com/Doraku/DefaultDocumentation#MarkdownConfiguration_IgnoreLineBreak) :) You can also locally change this settings in your xml elements by setting a `ignorelinebreak` attribute in your documentation `<summary ignorelinebreak="true">`

**Comment by madelson** [comment]
Perfect. I figured I was missing something. Updated doc looks great now. Any reason this isn't the default?

**Comment by Doraku** [comment]
Because I am lazy mainly haha, that's how I write my xml documentation even if I know it's not the proper way (as the intellisence display in visual ignores the line breaks), sorry ^^"

**Comment by madelson** [comment]
@Doraku haha ok. In that case would you be supportive of enabling this by default? My guess is that most people would want it, especially since as you say VS ignores these breaks anyway.

**Comment by Doraku** [comment]
Yeah even if it is a "breaking change" it shouldn't affect most people and it's better to be in line with how the intellisense behave.
