### ISSUE TITLE
not all XML comments are valid markdown

### ISSUE THREAD

**Issue by HuiyunPeng** [Doraku/DefaultDocumentation#126]
I have a XML comment like this:
```
<summary>
some comment...
var attr = member.GetAttribute[Type]();
</summary>
```

In the generated markdown, this `[Type]()` is treated as an empty link which is not what it supposed to be. It seems DefaultDocumentation is assuming that all XML comments are valid markdown. Do you want to consider validating XML comments before turning them into markdown?

**Comment by Doraku** [comment]
if you type code in your documentation you should use [`<c>` or `<code>`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#c) so it is properly escaped in the documentation.

**Comment by madelson** [comment]
@Doraku in this particular case sure, but in general can't we only assume that xmldocs are XML-encoded? The characters `[]()` are special in Markdown but not in XML; I think they should be rendered as-is.

**Comment by Doraku** [comment]
I guess this is somewhat related to #117 in a more general way, I'll see if there is a way to handle this at the same time.
