### ISSUE TITLE
Configuration file is not in project folder

### ISSUE THREAD

**Issue by wrekklol** [Doraku/DefaultDocumentation#128]
I can't find the configuration file anywhere in my project folder. I'm not sure if it can't create it because my project contains a space in the path? 
In any case, I'm getting an error when generating documentation, and I'm guessing it is because the file it generates has a too long filename. I wanted to see if the configuration file could do anything about that.

Update: Found out I had to create the config myself, sorry for my stupidity. I changed the FileNameFactory and now everything works. :)

**Comment by Doraku** [comment]
Np sorry for the late reply glad you found out on your own!
