### ISSUE TITLE
Rebuild sometimes loses namespace on property

### ISSUE THREAD

**Issue by darknessgp** [Doraku/DefaultDocumentation#129]
I have wired up DefaultDocumentation to build with my solution of multiple projects. It seems to work well, but we have ran into an issue of inconsistent changes around when namespace prefixes are included or not.

Say I have the below as a method.

```csharp
public System.BinaryData Data { get; set; }
```

Occasionally, about 1 every 5-6 builds. The markdown that comes out will remove the "System", so it looks like this:

```csharp
public BinaryData Data { get; set; }
```

The issue is we have all the markdown checked into a code repo. Because of the issue, depending on when someone commits, they are touching almost every markdown file.

**Comment by Doraku** [comment]
oh that's really weird, this is not something that should change. It is a public repo I can look into? Does DefaultDocumentation runs on the devs machine or on a build machine?

**Comment by darknessgp** [comment]
Unfortunately it is a private repo and work I am doing for a company. The maybe fortunate thing is that beginning around end of Sept, the issue magically stopped occurring. I am not sure why exactly, I am thinking maybe it had to do with updating Visual Studio 2022 to a newer version however.

**Comment by Doraku** [comment]
well I hope it won't be coming back then ^^" feel free to reopen this issue if you have new occurrence!
