### ISSUE TITLE
Sections for partial classes or regions

### ISSUE THREAD

**Issue by lufinkey** [Doraku/DefaultDocumentation#132]
Is there any way I could put the method definitions from "partial" classes into separate sections on the generated documentation page? The separate files have different method categories, so it would be easier for someone to read the documentation with these sections. This could also work with `#region`

**Comment by lufinkey** [comment]
Awesome, I'll check this out too when I get the chance. Thanks for your work on this awesome package, it was basically exactly what I needed for my project

**Comment by Doraku** [comment]
cleaning up old issues, feel free to reopen if you still need assistance.
