### ISSUE TITLE
<see> tag doesn't use the href argument when specified

### ISSUE THREAD

**Issue by lufinkey** [Doraku/DefaultDocumentation#133]
One of the arguments of the [&lt;see&gt;](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#see) tag is the href argument where you can manually specify a link. If this link is specified, it should override the auto-generated microsoft link

**Comment by Doraku** [comment]
It should actually handle it, but only if there is no `cref` attribute, it's one or the other, you are not supposed to have both.

**Comment by lufinkey** [comment]
Got it, thanks!
