### ISSUE TITLE
Cannot work out the format of the configuration file.

### ISSUE THREAD

**Issue by robbyxp1** [Doraku/DefaultDocumentation#134]
Hi,

I've updated, from 0.7.9, and now its not working, due to some options moving to the configuration file.

For the life of me, i can't see your documentation on the json format of this file.  All you stated is 

    configuration file: "Markdown.RemoveFileExtensionFromUrl": "..."

What does this mean? is it like this?

{
    "Markdown": {
        "RemoveFileExtensionFromUrl": true
    }
}

or just "Markdown.RemoveFileExtensionFromUrl":true in the top level object?

Many thanks

Rob

**Comment by Doraku** [comment]
Hello, that would be the second one :)
```json
{
  "Markdown.RemoveFileExtensionFromUrl": true/false
}
```

**Comment by robbyxp1** [comment]
Thanks, i'll give it a try tomorrow.

**Comment by Doraku** [comment]
cleaning up old issues, feel free to reopen if you still need assistance.
