### ISSUE TITLE
Compatibility with Statiq?

### ISSUE THREAD

**Issue by phmatray** [Doraku/DefaultDocumentation#136]
Hello, 
I was looking for an alternative to docFX and I'm very happy to have discovered DefaultDocumentation and to use it.

Also I have a question, what would be the best way to use the generated markdown as input for [Statiq](https://www.statiq.dev/docs)? It doesn't seem to be missing much but I'm having trouble with the link generation.

**Comment by Doraku** [comment]
cleaning up old issues/discussion to keep relevant stuff, feel free to reopen if needed as I'm not sure what is missing to make Statiq happy. You can now change the (url format)(https://github.com/Doraku/DefaultDocumentation#MarkdownConfiguration_UrlFormat) used in case it can help 🤔
