### ISSUE TITLE
<para> tag is ignored

### ISSUE THREAD

**Issue by adlerzei** [Doraku/DefaultDocumentation#138]
When I use the [\<para\> tag](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#para) in my \<code\> blocks, it is simply ignored by DefaultDocumentation.

**Comment by Doraku** [comment]
`<code>` blocks are used to display their content "as is" in a code format. What would you expect a `<para>` element to do in there?

**Comment by adlerzei** [comment]
You are right. I will close this.
