### ISSUE TITLE
Exception is thrown when there is a property with dynamic type

### ISSUE THREAD

**Issue by Maxime302** [Doraku/DefaultDocumentation#14]
The switch in DocumentationWriter (line 92) does not take the dynamic type into account and it throws a NullreferenceException when trying to call type.GetDefinition() in the default bahaviour of the switch.

**Comment by Doraku** [comment]
I... actually never use that keyword so it completely flew over my head! Thank you for bringing this up.
What do you think would be a good fallback documentation page? Would [this one](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/using-type-dynamic) fit the bill? I found [this one](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/reference-types#the-dynamic-type) also but it has less content.

**Comment by Maxime302** [comment]
I guess the first one is better, it's more complete. Thanks for the fix and for this great tool! That's very useful.

**Comment by Doraku** [comment]
Juste published v0.6.1 with the fix ;)
Glad you like it, I haven't given it much time to close the remaining big issues but if you have other small problems don't hesitate!
