### ISSUE TITLE
Option to validate uris?

### ISSUE THREAD

**Issue by bucurb** [Doraku/DefaultDocumentation#140]
I'd like to generate documentation for just the public entities in the assembly, but by mistake, some of their comments are referencing private members through <see cref...>. Is there a way the tool could raise errors for these cases instead of generating valid output with broken URLs? Alternatively, is there an option to validate the URLs it produced once it's done generating the output?

**Comment by Doraku** [comment]
Pretty late reply sorry but the way I see it you could create a new `IUrlFactory` to decorate the existing `DocItem` one, something like this:
```csharp
public class DocItemUrlValidator : IUrlFactory
{
    private readonly IUrlFactory _docItemFactory;

    // that way your new factory directly override the existing one, no need to change the configuration
    public string Name => _docItemFactory.Name;

    public DocItemUrlValidator()
    {
        _docItemFactory = new DefaultDocumentation.Markdown.UrlFactories.DocItemFactory();
    }

    public string? GetUrl(IPageContext context, string id)
    {
        string? url = _docItemFactory.GetUrl(context, id);

        if (url != null)
        {
            // the doc item is known, no issue
            return url;
        }

        if (id.Contains("Whatever your namespace is")
        {
            throw new Exception($"{id} should not be referenced in documentation");
        }

        // pass the relay to the next IUrlFactory, DotnetApiFactory by default
        return null;
    }
}
```

As this is an old issue I'll close it but feel free to reply if you need more help.
