### ISSUE TITLE
Filename ist to long than is support by the Filesystem

### ISSUE THREAD

**Issue by schefbi** [Doraku/DefaultDocumentation#15]
Thank you for the very useful package, I like it.

I have a problem with the file length. In our project, the namspaces, class, method... are really long. We get a error that the filename is too long. is there a option?

**Comment by Doraku** [comment]
There isn't one but it could be a good addition as it can probably happen easily.
I could add a parameter that would generate an id for each page instead of the full name but it could change every time you add/remove a type/member or regenerate the documentation so it would be hard to link to a specific page in a stable way.
What do you think would be a good alternative? I will try to think of something more static.

**Comment by schefbi** [comment]
This is an example that will be very long. 

`Clx-EventoNG-Custom-Extension-JobsQvCandidate NumberGenerate-GenerateJobResultMessages(Clx-Evento-NG-Common-Models-Anmeldung-UpdateAnmeldungResult_Clx-Evento-NG-Common-Sdk-BatchJob-SdkBatchJobControllerProcessResult_int).md`

I could imagine that the project name "Clx-EventoNG-Custom-Extension" could be shortened or even omitted for all objects. Or directories could be created for all namespaces.

**Comment by Doraku** [comment]
This is approaching longcat level of length :o
Removing the common namespace would be a good start but it is only pushing the problem further, I want something more radical. I am thinking of generating a static hash code from the string full name of each member with an extra character different for each symbol type to reduce the risk of collision so all file name would not change between multiple generation. Or maybe just generate a md5, I will do some testing.

**Comment by Doraku** [comment]
Just released v0.6.2 with the new DefaultDocumentationFileNameMode parameter inside the csproj.
Values are:
- FullName: the default behavior, will use the fully qualified name of each member
- Md5: will do a Md5 of the full name of each member to produce shorter name (experimental)

**Comment by schefbi** [comment]
Really cool, thanks for that change. Now it works fine...
