### ISSUE TITLE
Ignore page generation for specific methods

### ISSUE THREAD

**Issue by HClausing** [Doraku/DefaultDocumentation#150]
Hi.

I would like to know if there're any possibility (withou writing a custom plugin) to avoid table link and page creation for specific methods, and keep for anothers by default:

![image](https://github.com/Doraku/DefaultDocumentation/assets/15158923/36c429b9-69ce-4554-8fb2-3ef367872bb6)

I just want to avoid method linking for this class, generating just a normal text for the Methods's names

Thanks.

**Comment by Doraku** [comment]
hey, really sorry for the long absence I'm slowly picking back my projects. In case you are still looking for an answer you could use the [exclude xml element](https://github.com/Doraku/DefaultDocumentation?tab=readme-ov-file#Overview_Exclude). Feel free to reopen if you need more help I should be quicker to respond ^^"

**Comment by HClausing** [comment]
Nice, thank you!
