### ISSUE TITLE
No document is generated after project build

### ISSUE THREAD

**Issue by ankushmadankar** [Doraku/DefaultDocumentation#153]
### Discussed in https://github.com/Doraku/DefaultDocumentation/discussions/152

<div type='discussions-op-text'>

<sup>Originally posted by **ankushmadankar** December 27, 2023</sup>
I have created fresh project and install Default Document [nuget ](https://www.nuget.org/packages/DefaultDocumentation) latest package (Version="0.8.2"). Updated the csproj file with following PropertyGroup

```
<PropertyGroup>
	..
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<DefaultDocumentationFolder>Documentation\Api</DefaultDocumentationFolder>
</PropertyGroup>

```
then I build soultion inside Visual Studio (Version 17.8.3) and no document is created. I am expecting .md file at location `BuildLocation\Documentation\Api`. Anything I am missing?

Everything seems working with version 0.8.1.

Attached sample project [DefaultDocumentationTest.zip](https://github.com/Doraku/DefaultDocumentation/files/13776153/DefaultDocumentationTest.zip)</div>

**Comment by jeffpatton1971** [comment]
FWIW I'm facing this issue as well, .net 7 classlibrary project, I get the XML output but not the associated MD

**Comment by ankushmadankar** [comment]
> FWIW I'm facing this issue as well, .net 7 classlibrary project, I get the XML output but not the associated MD

Couple of workaround worked for me:
1. Make use of 0.8.1 version.
2. Clone repo create local nuget and use that nuget if latest version is required.

**Comment by Doraku** [comment]
pretty late answer but the DefaultDocumentationFolder path is relative to the current directory, cleaning up old issues/discussion to keep relevant stuff, feel free to reopen if needed.
