### ISSUE TITLE
Need to prevent creation of documentation for files autogenerated by Mvvm Toolkit.

### ISSUE THREAD

**Issue by freebelion** [Doraku/DefaultDocumentation#160]
I am using DefaultDocumentation in a project of mine along with Mvvm Toolkit, and I and grateful for it, but I need a way to exclude files autogenerated by the Toolkit, which I can't even find.

**Comment by Doraku** [comment]
hey, does the autogenerated code is prefixed by some specific attribute/comment by any chance 🤔

**Comment by freebelion** [comment]
Thank you for your reply. I haven't seen anything different about the XML comments placed by the Mvvm toolkit. They are the usual <Summary> blocks. The ones that bother me are the XML comments placed in partial class files with .g.cs (or whatever) extensions. Those files aren't visible normally, so I don't know how to exclude them either. Since they are automatically generated, I can't put an <exclude> block to suppress them, because those files will be recreated at the next build. 
The toolkit are those comments on top of partial copies of my class header and the backing fields and they appear alongside my own XML comments. That's the clutter I would like to get rid of. The only practical solution for me would be to remove that clutter by hand, after the completion of my project.
Please, I really don't expect anyone to feel burdened by helping me, but in case anyone wants to take a closer look, my repository is at
https://github.com/freebelion/HurPsy
