### ISSUE TITLE
Nested types

### ISSUE THREAD

**Issue by nxrighthere** [Doraku/DefaultDocumentation#17]
Just noticed that nested types are not handled properly.

Code:
```csharp
// <summary>
/// Key codes
/// </summary>
public static class Keys {
    public const string MouseX = "MouseX";
    public const string MouseY = "MouseY";
    public const string MouseScrollUp = "MouseScrollUp";
    public const string MouseScrollDown = "MouseScrollDown";
    public const string MouseWheelAxis = "MouseWheelAxis";

    /// <summary>
    /// Gamepad
    /// </summary>
    public static class Gamepad {
        public const string LeftX = "Gamepad_LeftX";
        public const string LeftY = "Gamepad_LeftY";
        public const string RightX = "Gamepad_RightX";
        public const string RightY = "Gamepad_RightY";

        ...
```
Result:

![result](https://user-images.githubusercontent.com/8279330/81489547-0f6d7900-9290-11ea-8ed4-f49f27fe09c8.PNG)

I think nested classes should be located in `Keys` class under `Classes` section. 🤔

**Comment by Doraku** [comment]
I took the way microsoft presents its own documentation as a reference ([example](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic?view=netframework-4.5)) but it wouldn't hurt to add those links on the parent type page too.

**Comment by nxrighthere** [comment]
Ah I see, thanks. Maybe we can make it optional?

**Comment by Doraku** [comment]
I added an enum you will be able to set with the `DefaultDocumentationNestedTypeVisibility` element in your csproj. I think the values should be self explanatory ;)
```csharp
    public enum NestedTypeVisibility
    {
        Namespace,
        DeclaringType,
        Everywhere
    }
```

**Comment by nxrighthere** [comment]
Looks nice, thanks!
