### ISSUE TITLE
Relative paths for generated documentation

### ISSUE THREAD

**Issue by nxrighthere** [Doraku/DefaultDocumentation#20]
I just discovered that relative paths like this `<DefaultDocumentationFolder>.../.../.../API</DefaultDocumentationFolder>` seems to work incorrectly. Folders with `...` in names are created instead, and this drives the Windows Explorer crazy, it won't let you delete such folders, the only way to delete them is to use the command-line.

**Comment by Doraku** [comment]
Shouldn't it just be '..' instead of '...'? Or do you actually want a folder named '...'?

**Comment by nxrighthere** [comment]
I think I should sleep more these days... Sorry.

**Comment by Doraku** [comment]
We all have those moments haha don't worry.
