### ISSUE TITLE
File name with generic types causes issues with DevOps wiki

### ISSUE THREAD

**Issue by TroySi** [Doraku/DefaultDocumentation#24]
I'm using this great tool to generate markdown files specifically for my DevOps wiki.  So far everything works great except one weird thing, if the file name ends in a "-" DevOps can't find it.  For example MyAssembly-MyClass-T-.md will not show in their wiki.  Granted this is a DevOps issue but I'm not sure what it would take to get them to fix this as for the most part they've haven't improved on this "feature" in a while.  I pulled down your code to test some things out and I tried using an underscore instead of the dash and that seemed to fix my problem.  Not sure if this is an option for your code or if the dash is following a certain naming convention, but I'd thought I'd let you know in case others find this tool and want to use it in DevOps as well.

**Comment by Doraku** [comment]
That's a pretty weird quirk of the DevOps wiki haha.
I wouldn't say I tried to follow some big naming convention when deciding what char replaces what, it's just that I wanted to differentiate between `,` and all the other special chars part of the name of a member `<>[].` to limit possible collision.
Changing the char might annoy some users as it would break current links to their documentation, best I could do is make the override char a parameter of DefaultDocumentation, default value being `-`.

**Comment by TroySi** [comment]
Agreed it would annoy users.  Perhaps maybe adding another fileNameMode option?  If not an additional parameter would certainly work as well.  Thank you.
