### ISSUE TITLE
Add support for constant field values

### ISSUE THREAD

**Issue by petarpetrovt** [Doraku/DefaultDocumentation#28]
Currently `DefaultDocumentation` dosen't show the constant field values.

Example:
```csharp
/// <summary>The maximum value.</summary>
public const int MaxValue = 3;
```

Generates:
## MaxValue Field
The maximum value.
```csharp
public const MaxValue;
```
#### Field Value
[System.Int32](https://docs.microsoft.com/en-us/dotnet/api/System.Int32 'System.Int32')

**Comment by Doraku** [comment]
Good suggestion, this also got me to see that the field type is omitted in the declaration, I will remedy to this :)
