### ISSUE TITLE
Add support for excluding specific type, property, method, etc..

### ISSUE THREAD

**Issue by petarpetrovt** [Doraku/DefaultDocumentation#29]
Possible tag  `<exclude/>` similar to NDoc and Sandcastle - [stackoverflow](https://stackoverflow.com/a/19653473/3323071).

Example:

```csharp
#if NETSTANDARD1_3
namespace System.Diagnostics.CodeAnalysis
{
	/// <exclude/>
	[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Event, Inherited = false, AllowMultiple = false)]
	internal sealed class ExcludeFromCodeCoverageAttribute : Attribute
	{
		/// <summary>
		/// Gets or sets the justification for excluding the member from code coverage.
		/// </summary>
		public string? Justification { get; set; }
	}
}
#endif
```

Should skip `ExcludeFromCodeCoverageAttribute` and don't generate documentation for `System.Diagnostics.CodeAnalysis` namespace.

**Comment by petarpetrovt** [comment]
I will close this issue as i have found alternative to exclude the code from docs and code coverage at the same time (for netstandard1.3)  - `System.Diagnostics.DebuggerNonUserCode`

**Comment by petarpetrovt** [comment]
Awesome! Thanks!

**Comment by petarpetrovt** [comment]
@Doraku When do you plan to release `v0.6.13` NuGet package ?

**Comment by Doraku** [comment]
This is kinda embarrassing, I wanted to do it yesterday but for some reason nuget.org is now refusing the `MIT-0` license while I had no problem previously ^^" I opened [an issue](https://github.com/NuGet/NuGetGallery/issues/8280) and await a resolution but if nothing comes up in the next couple of days I guess I will revert back to `MIT` to push this release.

**Comment by petarpetrovt** [comment]
Hello,

`/// <exclude/>`  dosen't work on methods.

Example:
```csharp
/// <exclude/>
public static void Test1() {}
```

I tested it with `0.0.0-ci20201118183225` NuGet package version.

Thanks
