### ISSUE TITLE
Exclude internal and protected internal methods and constructors

### ISSUE THREAD

**Issue by petarpetrovt** [Doraku/DefaultDocumentation#33]
Currently `DefaultDocumentation` doesn't skips methods or constructors if they are `internal` or `protected internal`.

**Comment by petarpetrovt** [comment]
The `<exclude />`  tag seems to fix the problem.
Tested on: 0.0.0-ci20201118183225 NuGet package version

**Comment by Doraku** [comment]
I hesitated to only generate documentation for public types and members but decided leave this decision to whether or not an xml documentation is present. Good thing you requested the `<exclude/>` tag haha.
Btw nuget.org still complains about my license, I will wait for the end of their current sprint to change it back to MIT if this is still not resolved >_>
