### ISSUE TITLE
0.6.13 seems to be able to get stuck in an infinite loop using inheritdoc

### ISSUE THREAD

**Issue by Ellpeck** [Doraku/DefaultDocumentation#35]
I don't know *exactly* what causes this issue to occur, but it doesn't happen in `0.6.12`, so I assume it's something about the [inheritdoc while loop](https://github.com/Doraku/DefaultDocumentation/blob/master/source/DefaultDocumentation/DocumentationGenerator.cs#L61) that was added in `0.6.13`.

[Here](https://gist.github.com/Ellpeck/1cfce97535c74bc043d7fa84c6f7ad7c) is a gist with an xml file that it happens with consistently, for testing purposes.

**Comment by Doraku** [comment]
Indeed I messed up >_> thanks for the heads up it shouldn't take long to fix.

**Comment by Ellpeck** [comment]
Great. Side question: Is there a way to make DefaultDocumentation put all of the information about methods, fields and properties of a class into a single file, rather than splitting it up into multiple? If there isn't, then I can open a separate issue with a suggestion if you're also interested in this behavior existing.

**Comment by Doraku** [comment]
Not currently, at first I intended to allow this kind of customization with #4 but as it hasn't moved at all (no epiphany on how to handle that yet) I might put some configuration to do just that. So yes, feel free to open an issue :) A refactoring of the pages generation is long overdue and it would be a nice thing to add.
