### ISSUE TITLE
Add a setting to put all of the info about a class into a single markdown file

### ISSUE THREAD

**Issue by Ellpeck** [Doraku/DefaultDocumentation#36]
> Is there a way to make DefaultDocumentation put all of the information about methods, fields and properties of a class into a single file, rather than splitting it up into multiple? If there isn't, then I can open a separate issue with a suggestion if you're also interested in this behavior existing.

(From https://github.com/Doraku/DefaultDocumentation/issues/35#issuecomment-780795071)

**Comment by Doraku** [comment]
Just putting some infos on what I have in mind for this: add a configuration element with an enum flag values
- Namespace: if not set, namespaces infos will be put inside the home page
- Type: if not set, types (class, struct, interface, enum, delegate) infos will be put inside the namespace page or home page if the Namespace flag is not set
- Member: if not set, members (constructor, field, property, method, event, operator) infos will be put inside the type page or namespace page if the Type flag is not set or home page if the Namespace flag is not set

By default all flags are set and produce the current behavior.

Still wondering if this is enough of if I need to give the same configuration choice for each type types  (class, struct, interface, enum, delegate) and member types (constructor, field, property, method, event, operator).
