### ISSUE TITLE
allow custom page generation

### ISSUE THREAD

**Issue by Doraku** [Doraku/DefaultDocumentation#4]
This goal is to allow the generation of a custom documentation (not necessarily in markdown format) if the default one does not suit users.
I tried to look into t4 before but couldn't managed to send the model to the page for some reason using [Mono.TextTemplating](https://www.nuget.org/packages/Mono.TextTemplating).
Other solution would be to use xslt (ewww) or give an interface to implement for the custom rendering (heavy and not really practical in my opinion).

Just putting it here in case someone with a bright idea happen to pass by.

**Comment by nxrighthere** [comment]
This overcomplicated stuff, it would be much easier to use any markdown page generator like [Markdeep](https://casual-effects.com/markdeep/) and if required and [rasterize](https://github.com/romainguy/markdeep-rasterizer) a static webpage from it.

**Comment by Doraku** [comment]
hum while interesting this is not completely what I had in mind with this issue. The end goal is to provide an API to expose all the elements of the documentation for user to customize what ends up in the produced documentation and in which order if ever (and in which format obviously).

**Comment by nxrighthere** [comment]
Ah, so a sort of templates system. It makes sense, yes.

**Comment by Doraku** [comment]
[mustache](http://mustache.github.io) looks interesting, the problem is how to handle text data which contains links, code, and other stuff which can be specific to a format (md, html, ...)

**Comment by IdkGoodName** [comment]
Liquid would make more sense, because if you are going to make a Github.io page, you'll end up using Liquid. Also, it's easier to understand it.

**Comment by IdkGoodName** [comment]
Or perhaps somehow make it available to build documentation using F#/[F# FAKE](/fsprojects/FAKE) or [C# CAKE](/cake-build/cake)?

**Comment by Doraku** [comment]
Just a small update on what is coming for the feature, in the end there won't be any real "template" but you will be able to provide your own implementations. Soon there should be a DefaultDocumentation.Api package exposing the full model used to generate documentation. You will be able to create implementation of `ISectionWriter` and `IElementWriter`.

An `ISectionWriter` is like a part of the documentation, for example currently there is a `SummarySection`, `TitleSection`, `RemarksSection`, ... You will be able to change the sections you want generated for your documentation with the `Sections` setting like so:
```
{
    "Sections": [
        "Header",
        "Default",
        "Footer"
    ]
}
```
It could either be the Name of the `ISectionWriter`, or the explicit type name `Namespace.TypeName Assembly` if you have multiple `ISectionWriter` with the same name and want to use an explicit one (by default it will take the latest available type with the searched name, you can add dll containing those implementation with the `Plugins` setting).

You will also be able to provide specific item sections that will not apply to other `DocItem` type
```
{
    "Sections": [
        "Header",
        "Default"
    ],
    "NamespaceDocItem": {
        "Sections": [
            "Header",
            "Summary",
            "TableOfContents",
            "Footer"
        ]
    }
}
```
In this case all pages will use the top level sections but for the `NamespaceDocItem` page, it will use those specific sections.

Maybe in the futur there will be plugins that give you `ISectionWriter` implementation that can actually use template to render but I think it is open enough like this :) 

It will also be possible to add custom tag support in the same way #79, I will rewrite completely the readme when the release is ready to reflect all those changes.
