### ISSUE TITLE
Add support for <list> balise

### ISSUE THREAD

**Issue by Doraku** [Doraku/DefaultDocumentation#44]
[reference](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/list)
Not sure how to handle, should be easy with a single line text but what about multiline? not sure markdown have a good alternative for this.

**Comment by IdkGoodName** [comment]
No idea if this is an answer you're looking for or if I am reading this issue wrong.

If you indent a line after list item, the indented line will be associated with the list item before the line. This is at least how GitHub flavoured Markdown works. Not sure if it's part of Commonmark.

```md
1. Item 1
2. Item 2
   Still item 2
3. Item 3
```
> 1. Item 1
> 2. Item 2
>    Still item 2
> 3. Item 3

**Comment by Doraku** [comment]
Just tried it I didn't know it auto indents newline like this. This is good to know :) Thx it should be possible to do something!
