### ISSUE TITLE
Add support for <permission> balise

### ISSUE THREAD

**Issue by Doraku** [Doraku/DefaultDocumentation#45]
[reference](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/permission)
I am really not sure what to do with this, if even something need to be done with it ^^"

**Comment by IdkGoodName** [comment]
Give it same treatment like with `<exception>` tag, but with `Permission` heading instead?

**Comment by Doraku** [comment]
Looking back at the reference, it seems Microsoft has removed the `<permission>` tag from recommended tags? So I guess even them don't know what to do with it, maybe I will just forget it ever existed and close this issue ^^".
