### ISSUE TITLE
Page file names are too long

### ISSUE THREAD

**Issue by IggaF** [Doraku/DefaultDocumentation#50]
Hi,

Currently I'm unable to generate pages for methods, because some of the md files have too long path.
Some of the build machines have older version of windows, hence have limitation on path length of 260 characters.
And when I try to generate pages for methods, a see paths longer than 300 characters...

I'm using 'Name'  option for pages.
I'm aware of MD5 option, but it's less convenient...

Maybe you can add another option to replace only method parameters with MD5?
I mean, name instead of:
  _ParentName.MethodName(method parameters...)_

would be something like:
  _ParentName.MethodName.MD5_

**Comment by Doraku** [comment]
Sure, it should be easy enough to add. Maybe a cleaner long terme fix would be to group methods by overload in the same page (#47) but it will be quicker to implement a new FileNameMode for now :)

**Comment by IggaF** [comment]
@Doraku  Thanks :)

**Comment by Doraku** [comment]
Waiting to see if an other issue is resolved before creating an official version but you can try the beta 0.7.4-beta1 to see if the names are ok for you with the new FileNameMode `NameAndMd5Mix`.

**Comment by IggaF** [comment]
@Doraku Thank you for being so responsive and adding it so quickly :)
Tested it - works great!
Thanks!
