### ISSUE TITLE
Suggestion: add table view for type members that have their own pages?

### ISSUE THREAD

**Issue by IggaF** [Doraku/DefaultDocumentation#51]
Hi,

Maybe you can add option to present Type members (properties, methods etc.) that have separate pages (according to DefaultDocumentationGeneratedPages) to be presented in a table?
Similar to Microsoft docs:
![image](https://user-images.githubusercontent.com/53037082/116542465-55827900-a8f5-11eb-9001-c50ebd04945e.png)

**Comment by Doraku** [comment]
Sadly there is nothing close to this in markdown syntax (can't have multiple line value in table to my knowledge in pure md) which is why I settled for the current listing. While you can use html tags to easily achieve this there is no guaranty that the markdown displayer will support it so that's why I tried to stay "md raw" (yes I know I use a html tag for relative page link but it is the only exception). To remedy this I am actually making good progress on the customization (#4) of the pages with liquid template so in a near futur you should be able to change the default template to use html tags if you know they are supported where your pages are displayed :)

**Comment by IggaF** [comment]
I meant to use extended md syntax: [https://www.markdownguide.org/extended-syntax/#tables](url)
I'm aware its not supported by all md editors (its written at the link above :) ), that's why I suggested to make it optional/configurable.
It just - table view is way more convenient to go over page contents, especially index page

**Comment by Doraku** [comment]
Yes but it would only work if your summaries are single line, which is not always the case for everyone :/ And I fear adding too much configuration point will transform DefaultDocumentation into what made me creates it in the first place, simplicity. That's why I prefer to go the road of custom template for this so people who wants more control can do it there.
Basically for this you would have to change the default template displaying members
```
### Methods
{%- for item in Items -%}
***
{{ item.Link }}  
{{ item.Summary}}
{%- endfor -%}
```
to something like this (if you know you only have one liner summaries)
```
| Methods | |
| --- | --- |
{%- for item in Items -%}
| {{ item.Link }} | {{ item.Summary}} |
{%- endfor -%}
```
(example not contractual!, the default template will not be just that)
That's the gist of it, I plan to give some example (like how to revert to the old list without the summary when displaying members) to help people start customizing but you would be able to do whatever you want.

**Comment by Onzi12** [comment]
Hi IggaF, Doraku,
A tabular view will make DefaultDocumentation **PERFECT!** 
The current list view makes the page very unclear and lengthy :\

Doraku,
maybe the "single line" constraint can be solved with an analysis of the summary for tags that creates new line(s):
``<br/>``  ``<para>``  ``</para>``  ``<para/>``
This way, DefaultDocumentation will know to add table-rows as needed.

What do you think?

You can read more on newline tags here: [How to add a line break in C# .NET documentation](https://stackoverflow.com/questions/7279108/how-to-add-a-line-break-in-c-sharp-net-documentation)

**Comment by Doraku** [comment]
hum that is quite interesting, I never noticed that VisualStudio actually ignore line break when showing intellisense :o
So it would make sens to rely on `<br/>` and `<para>` for multiline summaries in DefaultDocumentation to behave the same.
That would indeed fix part of the problem and kinda destroy my argument of not wanting to put html tag by default x) BUT nothing stop you to add `<code>` element in a summary and for markdown we definitely need a line break, making it impossible to show with markdown table syntax :(
Just tried html table too and cells content is not displayed as markdown so that's a no too >_>

My new idea: only show the first line of the summary when listing member (after all this is kinda a preview documentation of the member, not the full one) so we can use markdown table without problem.
Things to think about:
- you would still be able to have multiple line in the preview summary by using `<br/>` in your documentation and putting everyting on the same line
```
/// <summary>
/// blablabla<br/>blablabla
/// </summary>
```
| |
| --- |
| blablabla<br/>blablabla |
- if you use linebreak in your summary to not have long line, only the first part will be used (not sure to keep this as is or ignore ligne breaks like intellisense does :/)
```
/// <summary>
/// this line is
/// too long
/// </summary>
```
| |
| --- |
| this line is |
- same applied if the first element is a `param`
```
/// <summary>
/// <para>yello</para>
/// world
/// </summary>
```
| |
| --- |
| yello |
- skip any other tag like `<code>` to get the first text of the summary
```
/// <summary>
/// <code>
/// public void WhyWouldAnyoneDoThat();
/// </code>
/// seriously
/// </summary>
```
| |
| --- |
| seriously |

Do you think this behavior would be ok?

**Comment by Onzi12** [comment]
Besides programming, I'm also a UX researcher - so let me put my UX hat first: ``HAT ON``
Ok, so let's review the behavior you suggested from the user perspective. 

The user will use DefaultDocumentation with the goal of easily create beautiful documentation.
The "single line" behavior cannot be expected beforehand, so the user will run into it (or not) someday - and will be surprised by it.

I think it's safe to assume developers want a similar experience to what they are used to from IntelliSense,
And also, most likely you will never get a feature request from a user for this behavior.

If the original single-line constraint can be solved by:  
 1. Parsing the summary for the relevant tags
 2. Ignoring code tags (as it is a real technical problem)

I would go enabling it within this limitation. 

We can further learn on this issue by observing how others solved it in their documentation:  
[Microsoft's .NET]:  Multi lines are supported.  
[Google's Android]: Multi lines are supported.
[Apple's IOS]:          Multi lines are supported.

Though I don't usually tend to, here I would go with the flow.

[Microsoft's .NET]: https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=net-5.0
[Google's Android]: https://developer.android.com/reference/android/databinding/classes
[Apple's IOS]: https://developer.apple.com/documentation/appstoreconnectapi

**Comment by Doraku** [comment]
Thanks for your inputs @Onzi12. I am all for following the decision of greater minds on this! Going with the behavior of intellisense seems the more logical indeed. The fact that they added a `<para>` element for xml documentation just shows that you are not supposed to take line return into account I guess.
Now I am just wondering to do this the lazy way (lucky for us a single line break in markdown is ignored too, so it is a minimal code change on my side, but people would still be able to display a linebreak by putting two spaces at the end of the previous line, or two line break. Maybe this "magic" behavior could still be confusing) or put a little more effort into it (the method to display `<code>` and text element are the same in DefaultDocumentation. For code we want to keep line break! but for real text we remove every linebreak, forcing people to use `<br/>` and `<para>` to structure their description).

**Comment by Doraku** [comment]
small update and preview on this. I opted for a mix approached for now (line break in xml documentation are kept and replaced by `<br/>` element for preview). Here is the output of one file:


#### [DefaultEcs](DefaultEcs.md 'DefaultEcs')
### [DefaultEcs.System](DefaultEcs.md#DefaultEcs_System 'DefaultEcs.System')
## AComponentSystem&lt;TState,TComponent&gt; Class
Represents a base class to process updates on a given [World](AComponentSystem_TState_TComponent__World.md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.World') instance to all its components of type [TComponent](AComponentSystem_TState_TComponent_.md#DefaultEcs_System_AComponentSystem_TState_TComponent__TComponent 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.TComponent').  
```csharp
public abstract class AComponentSystem<TState,TComponent> :
DefaultEcs.System.ISystem<TState>,
System.IDisposable
```
#### Type parameters
<a name='DefaultEcs_System_AComponentSystem_TState_TComponent__TState'></a>
`TState`  
The type of the object used as state to update the system.
  
<a name='DefaultEcs_System_AComponentSystem_TState_TComponent__TComponent'></a>
`TComponent`  
The type of component to update.
  

Inheritance [System.Object](https://docs.microsoft.com/en-us/dotnet/api/System.Object 'System.Object') &#129106; AComponentSystem&lt;TState,TComponent&gt;  

Implements [DefaultEcs.System.ISystem&lt;](ISystem_T_.md 'DefaultEcs.System.ISystem&lt;T&gt;')[TState](AComponentSystem_TState_TComponent_.md#DefaultEcs_System_AComponentSystem_TState_TComponent__TState 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.TState')[&gt;](ISystem_T_.md 'DefaultEcs.System.ISystem&lt;T&gt;'), [System.IDisposable](https://docs.microsoft.com/en-us/dotnet/api/System.IDisposable 'System.IDisposable')  

| Constructors | |
| :--- | :--- |
| [AComponentSystem(World, IParallelRunner, int)](AComponentSystem_TState_TComponent__AComponentSystem(World_IParallelRunner_int).md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.AComponentSystem(DefaultEcs.World, DefaultEcs.Threading.IParallelRunner, int)') | Initialise a new instance of the [AComponentSystem&lt;TState,TComponent&gt;](AComponentSystem_TState_TComponent_.md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;') class with the given [World](AComponentSystem_TState_TComponent__World.md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.World') and [IParallelRunner](IParallelRunner.md 'DefaultEcs.Threading.IParallelRunner').<br/> |
| [AComponentSystem(World, IParallelRunner)](AComponentSystem_TState_TComponent__AComponentSystem(World_IParallelRunner).md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.AComponentSystem(DefaultEcs.World, DefaultEcs.Threading.IParallelRunner)') | Initialise a new instance of the [AComponentSystem&lt;TState,TComponent&gt;](AComponentSystem_TState_TComponent_.md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;') class with the given [World](AComponentSystem_TState_TComponent__World.md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.World') and [IParallelRunner](IParallelRunner.md 'DefaultEcs.Threading.IParallelRunner').<br/> |
| [AComponentSystem(World)](AComponentSystem_TState_TComponent__AComponentSystem(World).md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.AComponentSystem(DefaultEcs.World)') | Initialise a new instance of the [AComponentSystem&lt;TState,TComponent&gt;](AComponentSystem_TState_TComponent_.md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;') class with the given [World](AComponentSystem_TState_TComponent__World.md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.World').<br/> |

| Properties | |
| :--- | :--- |
| [IsEnabled](AComponentSystem_TState_TComponent__IsEnabled.md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.IsEnabled') | Gets or sets whether the current [AComponentSystem&lt;TState,TComponent&gt;](AComponentSystem_TState_TComponent_.md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;') instance should update or not.<br/> |
| [World](AComponentSystem_TState_TComponent__World.md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.World') | Gets the [World](World.md 'DefaultEcs.World') instance on which this system operates.<br/> |

| Methods | |
| :--- | :--- |
| [Dispose()](AComponentSystem_TState_TComponent__Dispose().md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.Dispose()') | Does nothing.<br/> |
| [PostUpdate(TState)](AComponentSystem_TState_TComponent__PostUpdate(TState).md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.PostUpdate(TState)') | Performs a post-update treatment.<br/> |
| [PreUpdate(TState)](AComponentSystem_TState_TComponent__PreUpdate(TState).md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.PreUpdate(TState)') | Performs a pre-update treatment.<br/> |
| [Update(TState, Span&lt;TComponent&gt;)](AComponentSystem_TState_TComponent__Update(TState_Span_TComponent_).md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.Update(TState, System.Span&lt;TComponent&gt;)') | Update the given [TComponent](AComponentSystem_TState_TComponent_.md#DefaultEcs_System_AComponentSystem_TState_TComponent__TComponent 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.TComponent') once.<br/> |
| [Update(TState, TComponent)](AComponentSystem_TState_TComponent__Update(TState_TComponent).md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.Update(TState, TComponent)') | Update the given [TComponent](AComponentSystem_TState_TComponent_.md#DefaultEcs_System_AComponentSystem_TState_TComponent__TComponent 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.TComponent') once.<br/> |
| [Update(TState)](AComponentSystem_TState_TComponent__Update(TState).md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.Update(TState)') | Updates the system once.<br/>Does nothing if [IsEnabled](AComponentSystem_TState_TComponent__IsEnabled.md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.IsEnabled') is false or if there is no component of type [TComponent](AComponentSystem_TState_TComponent_.md#DefaultEcs_System_AComponentSystem_TState_TComponent__TComponent 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.TComponent') in the [World](AComponentSystem_TState_TComponent__World.md 'DefaultEcs.System.AComponentSystem&lt;TState,TComponent&gt;.World').<br/> |

**Comment by Onzi12** [comment]
My friend, it looks **beautiful!**
Great job! 
I will test the beta on my API.

The file you sent behaves very well on my phone screen - supports the wrapping and long words in a user friendly way. 

Any specific reason for the mixed approach?

**Comment by Doraku** [comment]
> Any specific reason for the mixed approach?

I am still kinda torn on this, some intellisense behaviors just make no sense to me (you can't have multiple spaces, it will only display one). I hate this "you don't get what you type" approach and the need to rely on some balises. But maybe I am alone in expecting things to work like this and I should just listen to the voice of reason.

**Comment by IggaF** [comment]
@Doraku  I've tested last beta, table view looks **reallllllyyyy** good.
Thanks a lot :)
