### ISSUE TITLE
Please support dotnet below net5.0 in console tool (at least anetcoreapp3.1 as netcore LTS version)

### ISSUE THREAD

**Issue by mcpride** [Doraku/DefaultDocumentation#66]
At first ... thanks for your excellent work!

I tried to use your tool with the newest version 1.1.0 of cake build tools which natively supports the dotnet tool handling. But it fails on our build server because there are just LTS versions of dotnetcore installed and allowed. 

So please add at least netcoreapp3.1 as build target, e.g.:

`<TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>`

**Comment by Doraku** [comment]
Does dotnet tool package installation actually support multiple target frameworks? I will try it and see how it behave. At worst I could just change the current target to netcoreapp3.1 only since it is the current LTS as you said.

**Comment by mcpride** [comment]
It should be supported. The cake tool does the same: https://github.com/cake-build/cake/blob/develop/src/Cake.DotNetTool.Module/Cake.DotNetTool.Module.csproj
