### ISSUE TITLE
Missing information (<b> tag) in namespace table documentation

### ISSUE THREAD

**Issue by petarpetrovt** [Doraku/DefaultDocumentation#67]
DefaultDocumentation: `0.7.6-beta1`
TargetFramework: `NET6.0`

Code:
```csharp
/// <summary>
/// Represents a <b>16</b> bit handle in <b>I08V08</b> format.
/// </summary>
/// <remarks>
/// <br>- <b>08</b> bits for the handle index (<i>0</i> - <i>254</i>)</br>
/// <br>- <b>08</b> bits for the handle version (<i>0</i> - <i>255</i>)</br>
/// <br>- index <i>255</i> is reserved for <b>NULL</b></br>
/// </remarks>
public readonly struct I08V08Handle
```
Generated namespace docs:
![doc-namesapce](https://user-images.githubusercontent.com/7642579/129471843-c369e4d4-e123-4d2b-8ab4-81dcb31849fd.PNG)

Generated struct docs:
![doc-struct](https://user-images.githubusercontent.com/7642579/129471845-c631f2db-24ec-4796-9185-cfd90d8488b7.PNG)

**Comment by Doraku** [comment]
ah yes this is the problematic line
https://github.com/Doraku/DefaultDocumentation/blob/6441ea912d21a3323ee791c4c6c50616d2501555/source/DefaultDocumentation.Common/Writer/MarkdownWriter.cs#L261
The condition is too greedy I will see what I can do. (the idea was to ignore stuff like `<code>` element which can't be rendered in a single line with for the table preview)
