### ISSUE TITLE
Allow setting assembly URLs

### ISSUE THREAD

**Issue by IdkGoodName** [Doraku/DefaultDocumentation#68]
Allow us to set documentation URLs for assemblies. My project is split into multiple assemblies and generated code from parent assembly assumes that types from child assembly are from MS.

**Comment by Doraku** [comment]
This should be handled by using the [external links feature](https://github.com/Doraku/DefaultDocumentation#Links). If you also use DefaultDocumentation on your child assembly, you can make it generate the link file automatically and then reference it in the parent assembly with a `<DefaultDocumentationExternLinksFiles>` property.
