### ISSUE TITLE
Better format for md files.

### ISSUE THREAD

**Issue by botteroxom** [Doraku/DefaultDocumentation#93]
Currently I'm using this library to feed by CI/CD docussaurus 2

But the way it handles md files differ from vscode preview for instance.

would be possible to always have an empty line previous any 
### ```cssharp

and also previous to 
### `parameter`

so intead of 

```
_foldersPath'></a>
`foldersPath`
```

we would have 
``` 
_foldersPath'></a>

`foldersPath`
```

using prettier in vscode usually fix the problem.. 

but would be nice if it is embed instead of setting Github actions only for it.

**Comment by Doraku** [comment]
hum I think it doesn't make any difference for most markdown render engines so why not :)
