### ISSUE TITLE
Folders structure for each class

### ISSUE THREAD

**Issue by HClausing** [Doraku/DefaultDocumentation#94]
First of all, congratulations for this excelent job!

I would like to request an enhancement: The possibility to include sub-folders (and correct links) for generated .md docs for classes.

Example:

Current:
![image](https://user-images.githubusercontent.com/15158923/143235068-087b5d58-8b7e-41ed-9f3a-a3673331f94e.png)

Proposed (maybe something like this, or another idea):
![image](https://user-images.githubusercontent.com/15158923/143235270-6b5cbaff-692b-4d14-a61c-4f599193a94d.png)

Thanks.

**Comment by Doraku** [comment]
I think this would be a good case to make a plugin example of how to extend the existing generation. I will try to do it.

**Comment by HClausing** [comment]
Nice, thank you.

**Comment by Doraku** [comment]
Not directly in DefaultDocumentation but easily doable as a plugin as shown in the [sample](https://github.com/Doraku/DefaultDocumentation/tree/master/source/Sample). I hope that's ok for you, there can be multiple ways of doing sub folders so you are free to customize it as you need it :)
Maybe I will add it to the available default file name factories later.

**Comment by HClausing** [comment]
Nice news! Thank you so much!

I like so much your ideia do use a plugin system to attend many different requests"
