### ISSUE TITLE
Generate YAML front-matter for Jekyll

### ISSUE THREAD

**Issue by IdkGoodName** [Doraku/DefaultDocumentation#95]
Currently, DefaultDocumentation only generates plain Markdown document without any YAML front-matter. This can be bothering if you use any SSG like Jekyll to document your library.

Current page generation:
````markdown
### [X](...)
## [X.Y](...)
# [X.Y.Z](...)

Summary
```csharp
public class Z : α
```
<!-- ... -->
````

Suggested page generation:
````markdown
---
title: X.Y.Z
member_type: class
description: >
  Summary
definition: >
  public class Z : α
---
### [X](...)
## [X.Y](...)
# [X.Y.Z](...)

Summary
```csharp
public class Z : α
```
<!-- ... -->
````

Perhaps even possibly allow setting which properties to add.

**Comment by Doraku** [comment]
With the new feature allowing you to add custom sections, you should be able to add just that. I am still cleaning up some stuff and adding documentation to the api but a plugin example of how to add new features should arrive soon.

**Comment by Doraku** [comment]
I added in the [samples](https://github.com/Doraku/DefaultDocumentation/tree/master/source/Sample) an example of a basic custom section, you could use that to prefix all your pages with what you need.
