### ISSUE TITLE
Missing extensions for api

### ISSUE THREAD

**Issue by IdkGoodName** [Doraku/DefaultDocumentation#98]
Extensions like `AppendAsMarkdown`, `AppendLink`, `writer.GetCurrentItem` are missing in DefaultDocumentation.Api package. You have to paste the code from DefaultDocumentation as of now.

**Comment by IdkGoodName** [comment]
As an addition, it would be nice if definition generation would also be made as an extension.

**Comment by Doraku** [comment]
It is actually deliberate, I wanted to keep the Api free of any markdown specifics and later publish the DefaultDocumentation.Markdown package for people to use if they wish to add features specifically for the markdown generation. The Api package could be used to generate extra format documentation (html, pdf, ...) without the markdown fluff.
Sadly I have been quite busy with work lately and I will use the holidays for a nice break :D I hope to finish with this task at the start of next year. For the most part I think the Api package is quite clean, I am just having second though on the `IGeneralContext.GetUrl` methods.

**Comment by Doraku** [comment]
The big update is now live. I can prepare the DefaultDocumentation.Markdown project for publishing next :) I hope I won't take as long as for the api haha

**Comment by IdkGoodName** [comment]
Sorry for bothering or bumping this issue, but half a year is kind of freezing my project's documentation updates.

**Comment by Doraku** [comment]
sorry for the huuuuge delay, lot of stuff happened in my professional & personal life so I didn't have much time. Now that things have calmed down a little (at least on the personal side haha) I should be able to get back to it. A lot of stuff people are asking rely on this so it'll be my main focus for now.
